struct OceanMaterialUniform {
    seed: i32,
    sea_level: f32,
    continental_freq: f32,
    continental_amp: f32,
    continental_octaves: i32,
    mountain_freq: f32,
    mountain_amp: f32,
    mountain_octaves: i32,
    hill_freq: f32,
    hill_amp: f32,
    hill_octaves: i32,
    detail_freq: f32,
    detail_amp: f32,
    detail_octaves: i32,
    warp_freq: f32,
    warp_amp: f32,
    lacunarity: f32,
    gain: f32,
    _pad0: f32,
    _pad1: f32,
    planet_radius: f32,
    elevation_scale: f32,
    sun_dir_x: f32,
    sun_dir_y: f32,
    sun_dir_z: f32,
    time: f32,
    camera_pos_x: f32,
    camera_pos_y: f32,
    camera_pos_z: f32,
}

@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<uniform> ocean_material: OceanMaterialUniform;
